removed tables
tables==3.4.4
error message:
Complete output from command python setup.py egg_info:
           * Using Python 3.7.2 (default, Jan 29 2019, 19:41:29)
           * USE_PKGCONFIG: True
           /tmp/H5closek9d4tn5t.c:1:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
            main (int argc, char **argv) {
            ^~~~
           /tmp/H5closek9d4tn5t.c: In function ‘main’:
           /tmp/H5closek9d4tn5t.c:2:5: warning: implicit declaration of function ‘H5close’ [-Wimplicit-function-declaration]
                H5close();
                ^~~~~~~
           /usr/bin/ld: cannot find -lhdf5
           collect2: error: ld returned 1 exit status
           .. ERROR:: Could not find a local HDF5 installation.
              You may need to explicitly state where your local HDF5 headers and
              library can be found by setting the ``HDF5_DIR`` environment
              variable or by using the ``--hdf5`` command-line option.
           
           ----------------------------------------
       Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-mbuxvjru/tables/